In [21]:
from sklearn import preprocessing
import pandas as pd
from numpy import set_printoptions
from sklearn.preprocessing import Normalizer

In [22]:
iris_df = pd.read_csv('https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv')
iris_temp = iris_df
iris_temp=iris_temp.drop(columns=['species'])
array = iris_temp.values

In [23]:
Data_normalizer = Normalizer(norm='l1').fit(array)
Data_normalized = Data_normalizer.transform(array)

In [24]:
set_printoptions(precision=2)
print ("\nNormalized data:\n", Data_normalized [0:5])


Normalized data:
 [[0.5  0.34 0.14 0.02]
 [0.52 0.32 0.15 0.02]
 [0.5  0.34 0.14 0.02]
 [0.49 0.33 0.16 0.02]
 [0.49 0.35 0.14 0.02]]


In [25]:
Data_normalizer = Normalizer(norm='l2').fit(array)
Data_normalized = Data_normalizer.transform(array)

In [26]:
set_printoptions(precision=2)
print ("\nNormalized data:\n", Data_normalized [0:5])


Normalized data:
 [[0.8  0.55 0.22 0.03]
 [0.83 0.51 0.24 0.03]
 [0.81 0.55 0.22 0.03]
 [0.8  0.54 0.26 0.03]
 [0.79 0.57 0.22 0.03]]
